version: "3.9"
services:
  server:
    build: ./backend
    image: backend
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  client:
    build: ./frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - C:\Users\Mark\Code\political_bots_mvp\frontend\political_bots_frontend\:/app
    image: frontend
    ports:
      - "3000:3000"