version: "3.9"
services:
  selenium-chrome:
    image: selenium/standalone-chrome
    hostname: selenium-chrome
    privileged: true
    shm_size: 16g
    ports:
      - 4444:4444
  scraper:
    build: ./scraper
    image: political_bots/scraper
    depends_on:
      - selenium-chrome
    volumes:
      - ./common:/app/common
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8